### PR TITLE
Layout and style touchups

### PR DESCRIPTION
**Pull request by alerque**
I think this covers the rest of the outstanding regressions reported in the layout and style changes I made. Most of this is very messy—the only reason these things broke is because they were not proper use of markup or styles in the first place and these fixes don't address the root problems—but they should tide folks over until each area gets a proper overhaul.

### CODE REVIEW

**Comment by teusbenschop** [comment]
The fix that maps the styling of the interlinear resources to external site's css would work in case the resource content is freshly fetched from the external website. But in case the resource has been cached locally in Bibledit (which in more recent versions is called to "install" a resource), it won't work because the content is not fetched afresh.

**Comment by teusbenschop** [comment]
Thank you for fixing the burndown chart and the Hebrew resources - that helps a lot!

**Comment by alerque** [comment]
> But in case the resource has been cached locally in Bibledit (which in more recent versions is called to "install" a resource), it won't work because the content is not fetched afresh.

I can't get my head around what you're saying there. It shouldn't matter at all since I stuck the mapping in the master CSS file. It might be _duplicated_ with the inline CSS injected into the resource if that got cached, but it should work in both scenarios. If I'm missing something here you might have to at least point me in a direction....

**Comment by teusbenschop** [comment]
Uhm, I think you are right - sorry for the confusion. Indeed, the fix should work under all circumstances :)

**Pull request merged**
