### PR TITLE
[WIP] Refactor layout code using border-box sizing

### PR DESCRIPTION
**Pull request by alerque**
There was a time we had to fight 100% of anything being wider than its parent. That time has past. The CSS box sizing model [has been fixed](https://css-tricks.com/box-sizing/) for a while now. Switching to it makes all sorts of things easier and obsoletes a lot of assorted layout and style hacks.

This is a work in progress, but I thought I'd  open the conversation now because I don't know what all I need to test for. So far this set of fixes does more than one thing:
1. It switches to a border-box model. This means that 100% of a container is 100% of its parent, not of the window.  Margins, borders and padding are _inside_ the box not outside.
   
   In order to make good use this, all the workbench sizes need to be refactored so that all the sizes add up to 100% instead of  something arbitrarily less than that.
2. It switches to a fixed height top bar so that the page doesn't change layout as items in the menu change.
   
   This isn't finished as I would like to cleanup the menu system using CSS instead of page rebuilds. Right now the menu is a royal pain to use and look around the app. If you know what you want already it works, but if you are exploring it's confusing as can be.
   
   I would like to refactor it so that the whole menu structure is always loaded in the page and CSS rules highlight the active item, show/hide the right child menus, and obsolete the breadcrumbs system. The layout changes here are just a band-aid to stay functional until those changes make it look and work better.
3. Cleanup other odds and ends like how the splash is composed, what containers generate margins so they  are more consistent overall, etc.

Known todo items before merging:
- [x] Fix default workbench layouts
- [x] Check print layout
- [x] Check mobile layouts
- [x] Fix font size jump increments
- [ ] Make sure scrolling works across all platforms
- [x] Purge any remaining height/width hacks

What else needs to be considered to roll this out?

### CODE REVIEW

**Comment by teusbenschop** [comment]
The idea of getting rid of sizes as defined in CSS and moving to CSS3, looks appealing.

As for testing it, most problematic have been the embedded browser as used in Android, and worse still is the embedded browser as used in iOS. Those are stock browsers.

The Android one does not behave very well when it comes to workbenches.
The iOS one is worse.

For moving to CSS menus, items to test it on is the mobile devices. There used to be a crash in the Android embedded browser when using a CSS based menu.
There is also a discussion on the bibledit-general list about how difficult it is to tap the menus when using a CSS menu, because there's no option to "hover" over a menu on mobile devices.
Mobile apps do not usually have CSS menus that extend when hovering over them because those apps don't know about hovering.
I believe that these are the main items to test when moving to the new menu.

**Comment by alerque** [comment]
Ummm...I didn't intend this to be merged until those items were addressed. Did you mean to do that?

**Comment by teusbenschop** [comment]
The fixed width for the menu takes some screen space away from the visual Bible editor, and on mobile devices such screen space is precious.

screen shot 2016-03-26 at 12 55 52

**Comment by teusbenschop** [comment]
Ah, yes, I thought that the items were to be merged, but have reverted now - thanks for the remark :)

**Comment by alerque** [comment]
That concern can be addresses using flex boxes to determine the header height. I'm not sure how good mobile browser support is for that though. What is our lowest target version set?

**Comment by alerque** [comment]
[Flexbox support](http://caniuse.com/#feat=flexbox) doesn't look too bad except embedded Android Pre 4.3.

**Comment by teusbenschop** [comment]
For Android the lowest target is set in the build scripts as:
project.properties:target=android-20
And in real life, the statistics for installed devices look as in the screenshot below.
screen shot 2016-03-26 at 13 57 52

**Comment by teusbenschop** [comment]
What would be the advantage of flexboxes as compared to setting the height of the menu automatically by just not setting a height for it in the CSS?

**Comment by alerque** [comment]
You can't set the height automatically unless you recalculate the values using Javascript and catch every browser resize event. Ugly.

You can't just not set a height because then the body (workspace) doesn't know how much height it has to work with.

Flex box allows one object to take  up whatever space it needs and the other objet(s) to stretch to fit the remaining space. I have a working experimental version of it that seems promising. I'll post it in a second and you can check it out.

**Comment by teusbenschop** [comment]
Thanks for the explanation.

**Comment by alerque** [comment]
That Android 4.2 number is a bit rough. Does that mean everybody using the app is running the embedded browser from that era rather than an updated browser widget?

**Comment by alerque** [comment]
That Android 4.2 number is a bit rough. Does that mean everybody using the app is running the embedded browser from that era rather than an updated browser widget?

**Comment by teusbenschop** [comment]
Here is the Android code:

import android.webkit.WebViewClient;
....
webview = new WebView (this);
setContentView (webview);
webview.getSettings().setJavaScriptEnabled (true);
webview.getSettings().setBuiltInZoomControls (true);
webview.getSettings().setSupportZoom (true);
webview.setWebViewClient(new WebViewClient());
webview.loadUrl (webAppUrl);

It think it means that the app takes the WebView that happens to be on the device.
Whether the device updates the factory WebView, I think, depends on https://play.google.com/store/apps/details?id=com.google.android.webview.

**Comment by alerque** [comment]
So it looks like one  solution is to layout basic mode differently than advanced mode. The potential for different menu heights and the complexity of workbench layouts is only in the advanced mode anyway, and on mobile browsers default to basic mode already. Android 4.3 and up should be able to run flex box layouts just fine, and the people on 4.2 would have to use basic mode only. Does that  sound like a reasonable compromise?

A working flex-box layout is up on [this branch](https://github.com/alerque/bibledit/tree/flex-boxes). For best effect you need to edit the desktop layouts again. The values are no  longer percentages but factors. Setting all values to 1 will make all rows/columns the same size. Setting 2-3-1 will make the first column twice the size of the last column and the middle three times the size.

**Comment by teusbenschop** [comment]
That compromise sounds reasonable. Everyone can work with basic mode at least, and whoever wants more needs a newer device.
I like the idea of having factors rather than percentages/pixels. An automatic conversion routine from the current percentages/pixels to factors would be helpful, with the aim that the end-user does not notice anything after an upgrade (apart that it works more smoothly) :)
Thanks, bro, for the improvements.

**Comment by alerque** [comment]
Surprisingly no conversion is actually necessary. I tweaked the settings handling to drop the "units" and even old values _work_ as factors. For example 20% + 75% end up being factors of 20/75, which actually works fine. The same goes for pixel or other values entered. Those percentages _could_ be simplified to 1/4 or something like that, but it works just fine without simplification.

Even things that don't add up to 100 that only approximated a full screen before are adjusted to actually fit now.

**Comment by teusbenschop** [comment]
Wauw, that's great!

**Comment by alerque** [comment]
Can you explain what the logic was behind using `vh` units for font sizes?

**Comment by teusbenschop** [comment]
It is explained in https://css-tricks.com/viewport-sized-typography, and the idea was to make the font large enough for easily tapping the buttons and to make the text easily readable on mobile devices. The idea was that the CSS adapts the font size automatically to the various screens.

**Comment by alerque** [comment]
Alright. I get the theory but I'm going to suggest that this is some combination of a bad use-case and an incomplete implementation and it actually detracts from overall usability. I watched a user here futsing around with their setup trying to resize the browser window and using their browser's zoom function and unable to get the size they wanted. In testing the layout changes I've been using different browser widths and it's really strange that some widths (and I'm not talking super narrow here) have big typography  and then others small. Instead I would (and I think most users would) like to do the least-surprising thing of zoom to the text size they want (and/or use BE's base font size setting) and then set the browser size they want with the content width they want to use.

**Comment by teusbenschop** [comment]
I agree that resizing the width of the browser window leads to unexpected font sizes.

If you've got a better solution to the following problem, that would be great: 

What happens is that various devices with various screen sizes connect to the Cloud, and the goal is to give them an optimal first experience, such that the font size automatically is about right for their screen size. And that will be before they have logged in, or before they have found the setting for the general font size in Bibledit.

**Comment by alerque** [comment]
My suggestion is that optimal font sizes for each device is typically set by the device already. I would only use viewport sized typography in order to fit a specific graphic design element: for example in headers, menus, lightboxes, or other things that also scale at  width.  Using it for body text railroads users into something that could be a less than ideal reading experience. The flexible with + varying font size at different widths creates a uncomfortable (and unexpected) dissonance.

The PR I just opened to replace this one (you can edit commits in an open PR but  not a closed one) has an implementation of this using 100%/1em as the base font size and lets everything adjust from there. This looks great on my desktop and Android phone, but those are the only platforms I'm testing on at the moment.

**Comment by teusbenschop** [comment]
Yes, whatever is done to improve the visual appearance and easy of use for the user is good. If the new pull request looks great on your desktop, and on your Android phone, I'd expect that it also looks good on the notebooks and iOS devices. In my experience the iOS browser lacks behind in conformance compared to Android through. Once the pull request can be pulled in, I can test it on an iPad mini.

**Comment by alerque** [comment]
I fixed the merge issues (it had to be coaxed into rebasing against something that had been applied and reverted), but you should be able to checkout the branch and test without merging to GitHub too. You know you can add my fork as a remote in your git client so you can checkout my branches right?

**Comment by teusbenschop** [comment]
It sounds stupid but I just fail to get this branch when doing the following:

$ git clone https://github.com/alerque/bibledit.git
$ git branch

It only lists the master branch...
(I prefer to use the command line in this case just for clarity and knowing what to do).

**Comment by alerque** [comment]
Try `git fetch --all`, that should pull down all the available branches instead of just master. You could also just add in as a remote to your other repo, you don't have to clone a new one:

```
# From your existing repo:
cd /path/to/repo

# Add an extra remote (yours is probably called 'origin', you can name mine how you like)
git remote add alerque https://github.com/alerque/bibledit.git

# Get the latest commits from all remotes and all branches
git fetch --all

# Look at the available branches
git branch

# Checkout a local copy of my current flex box branch
git checkout -b test-flexbox alerque/layout-flex-box
```

**Comment by teusbenschop** [comment]
I got it working now from the command line, thanks for the pointers.

Here's two pictures of the visual chapter editor on Safari on iOS.

The first is the visual chapter editor of the current production software.

The second ons is same editor running on branch "layout-flex-box".

production

layout-flex-box

I have not yet tried the embedded webview of iOS, because since Safari is more capable (I think) than the embedded webview, it's enough for just now to notice a problem in Safari. I't running iOS 9.3, that is currently the newest version.

**Comment by alerque** [comment]
Hmmm, that's interesting. There must be some sort of box type inheritance issue going on there. Is this running is Basic mode?

**Comment by teusbenschop** [comment]
It is running in advanced mode (because the visual chapter editor is only available from that mode).

**Comment by alerque** [comment]
This isn't just an iOS problem, I duplicated the results in Safari on OSX so I'll be able to test it locally pretty easily. At this point it's going to be Monday before I'm coding on this again. He is risen!

**Comment by teusbenschop** [comment]
Amen!

**Comment by alerque** [comment]
I added some fixes that make Safari happy—at least the latest version on OSX. I don't have an iOS device or older versions to test on, but I suspect at least that particular issue is fixed across the board now.

**Comment by teusbenschop** [comment]
It looks nice now. See the screenshot below. The screenshot was taken from the "Simulator" app on OSX, which simulates an iPad Air in this case.

screen shot 2016-03-28 at 11 25 39

**Comment by alerque** [comment]
Looks good to me. Have you run into any other issues with the flex layout on any platforms?

**Comment by teusbenschop** [comment]
I have not really looked at desktop devices, thinking that desktop browsers are advanced enough to handle the flex layout. I ran it on OSX and that worked fine, and ran it on iOS, and that works fine now too, and you have tested Android, if I recall well, so my overall impression is that it probably is good enough to be used for production work. In case there's going to be problems on production devices, would you have a fix quickly?

**Comment by alerque** [comment]
I've tested Android, but only very new Android. It might be worth having somebody with an old device give it a poke.

I should have pretty quick turn around this week for anything we can put our fingers on. Next week I'll be traveling for a couple days and as my lappy burned up recently I won't be able to do as much hacking on the road.

**Comment by teusbenschop** [comment]
Perhaps asking on the list whether there's someone with an older device might help. There's also the Android emulators from Google that, I think, can emulate older Android versions.

**Comment by alerque** [comment]
I'm trying to setup Android testing stuff locally and reviewed what you'd said about target versions. On second look I'm a little confused by your build prop and [screen shot above](https://github.com/teusbenschop/bibledit/pull/99#issuecomment-201814268).

```
project.properties:target=android-20
```

Android API level 20 doesn't make much sense for this app as 20 is the point release to support Android Wear between 19 (KitKat/4.4) and 21 (Marshmallow/5.0). I have to imagine 20 is somehow compatible with 19 as well at least for app builds, so that leaves the app with support for devices running 4.4 or newer.

How then does the usage chart show so many active installs on 4.2 and 4.3? Are those old installs stuck on old versions? Or am I not interpreting the data correctly here?

**Comment by teusbenschop** [comment]
The app is using hardly anything of the Android API. Most is written in the native language. That is C++. I am on the road right now and don't have access to the code to check whether there's another number for the minimum version. If not, it is unclear what the app store is doing with the version numbers.

**Pull request merged**
