### PR TITLE
Refactor layout code using border-box sizing + flex box

### PR DESCRIPTION
**Pull request by alerque**
Note: _This is a re-submission of code from the prematurely merged issue #99 along with some new stuff that came out of the discussion there._

There was a time we had to fight 100% of anything being wider than its parent. That time has past. The CSS box sizing model [has been fixed](https://css-tricks.com/box-sizing/) for a while now. Switching to it makes all sorts of things easier and obsoletes a lot of assorted layout and style hacks.

This is a work in progress, but I thought I'd  open the conversation now because I don't know what all I need to test for. So far this set of fixes does more than one thing:
1. It switches to a border-box model. This means that 100% of a container is 100% of its parent, not of the window.  Margins, borders and padding are _inside_ the box not outside.
   
   In order to make good use this, all the workbench sizes need to be refactored so that all the sizes add up to 100% instead of  something arbitrarily less than that.
2. It switches to a fixed height top bar so that the page doesn't change layout as items in the menu change.
   
   This isn't finished as I would like to cleanup the menu system using CSS instead of page rebuilds. Right now the menu is a royal pain to use and look around the app. If you know what you want already it works, but if you are exploring it's confusing as can be.
   
   I would like to refactor it so that the whole menu structure is always loaded in the page and CSS rules highlight the active item, show/hide the right child menus, and obsolete the breadcrumbs system. The layout changes here are just a band-aid to stay functional until those changes make it look and work better.
3. Cleanup other odds and ends like how the splash is composed, what containers generate margins so they  are more consistent overall, etc.

Known todo items before merging:
- [x] Fix default workbench layouts
- [x] Check print layout
- [x] Check mobile layouts
- [x] Fix font size jump increments
- [ ] Make sure scrolling works across all platforms
- [x] Purge any remaining height/width hacks

What else needs to be considered to roll this out?

### CODE REVIEW

**Comment by teusbenschop** [comment]
Is this branch now ready for merge?

Reference: Discussion at https://groups.google.com/forum/#!topic/bibledit-general/uuM3-3muBnU

**Comment by alerque** [comment]
As far as I am aware of, yes. I haven't gotten very proficient at testing either across the range of devices or range of features yet so realistically all I can say is that It Works For Me™. If anything comes up with specific situations or devices I'll have some availability  to hack on them about every other day for the next few weeks. And I finally got my laptop replaced and am working on gearing it up for dev work so my times away from a dev computer should get less serious than they have been the last month.

**Comment by teusbenschop** [comment]
I have merged it with the main branch, and will now start testing the effects on the various devices to see how each device behaves. Thanks for the great improvement (I think). I'm looking forward to seeing how much better the menus are going to look and behave. I admit that my focus is not on CSS or beauty of interface, but rather on the bare functionality... 😄

**Comment by teusbenschop** [comment]
Question: What is file .csscomb.json for?

**Comment by teusbenschop** [comment]
In the desktop editor, setting the Desktop width: to e.g. 100% or 2000px no longer works. When leaving this empty, the desktops work as expected. When entering the above values, the desktops no longer display the contents of the iframes.

**Comment by teusbenschop** [comment]
The help information in the desktop editor still mentions percentages and pixels, but the percentages now have changed to factors, and the pixels do not seem to work (which is fine). It means that the help information does not now match with how it works.

**Comment by teusbenschop** [comment]
On the Mac, the link to clear the entire journal does not remain at the bottom of the page, but scrolls along with and mixes with the journal entries, leaving users in the dark about how to clear the journal as they don't find the link anymore in cases of long journals.
screen shot 2016-04-18 at 17 49 51

**Comment by teusbenschop** [comment]
The above occurs in the OSX port and also with Safari.

**Comment by teusbenschop** [comment]
On Android it fails to edit the Bible text. Although the text is supposed to be editable, it is not editable on a Nexus 6 running Android 6.0.1.

**Comment by teusbenschop** [comment]
On Android 6.0.1 the Bible text editor fails to operate the "Style" button, with the result that styles cannot be called or seen.

**Comment by teusbenschop** [comment]
On Android, when doing a search, then clicking the passage link in one of the search results, it says that the passage has been opened in the existing editor, yet it has not been opened at all.

**Comment by teusbenschop** [comment]
More has to be tested to see how it behaves, but the tests done so far show that the Android port is now crippled such that a translator cannot translate in it anymore. How can I revert this patch from the master branch (enabling continued development on that branch - it's stuck now) without disturbing this pull request?

**Comment by teusbenschop** [comment]
On iOS, the link for clearing the journal shifts off the screen also, like on OSX.

**Comment by teusbenschop** [comment]
The tables, for the sprint planner, are spread out over the whole width of the screen. This makes it hard, on a wide screen, to see which planned item is on which row. The tables used to not be spread out but to be formatted a narrow as was natural, for clarity.
It applies to other tables too, e.g. the tables for the Settings / Users.

**Comment by alerque** [comment]
> Question: What is file .csscomb.json for?

That's to help keep the CSS normalized. See the 0186c68 commit message.

I'll poke at these other things in a bit here, but it would be nice to have them as separate issues as I think each one of them is likely to need a separate fix.

**Comment by alerque** [comment]
> How can I revert this patch from the master branch (enabling continued development on that branch - it's stuck now) without disturbing this pull request?

Who besides you clones this repo and has pulled this merge in? @postiffm are you familiar with rebasaing? We can either force push an old version back on top of this (which screws not just the PR workflow but the commits that are already in there past this point) or just do other dev work on a branch starting from an old commit and we'll merge that back later:

```
git checkout -b devel 7a1777e
```

That being said the Android bugs don't sound that serious to me, but I won't know for sure until I can replicate them. Are you testing in a VM or or a device?

**Comment by teusbenschop** [comment]
Well, screwing up the workflow for the pull request is probably something
that can be done when there's an urgent need to release a new Android port,
but right now there is no immediate need for that. I am translating part of
the time on Android due to circumstances, and it means that when an update
is needed, I'll have to revert the commit made by this pull request but
expect this not to be needed.

Yes, probably postiffm would have pulled this merge in.

A simple $ git revert ... would also do it. It makes a reverse commit. And
the advantage of this would be that the commit made by this pull request
remains in the history. Still, it screws up the PR workflow.

I am wondering whether making pull requests for much smaller changes will
help situations like this. The changes will be so small that their
consequences can easier be seen or tested.

Glad to hear that the Android bugs don't sound serious to you. I am testing
on a real device, not on a VM.

**Comment by alerque** [comment]
Please don't `git revert` commits that are merges of whole branches. Having that in history is not a good thing as it completely ruins the git blame and git bisect commands. That already happened once with this PR and it's been much harder than it needs to be to track problems on this code since.

And yes in general smaller feature branches are preferred, but in this case this whole set of changes kind of needed to stay together. It either works as a set or not at all, there wouldn't be a way to introduce the overall layout change without breaking everything.

**Comment by teusbenschop** [comment]
Point about $ git revert noted...

**Pull request merged**
